<?php 
require_once('../config/functions/utilities.php');
$status_msg='';
        if(isset($_POST['create_user'])){
          
           $user_team_string = implode(',', $user_team);
            
            $if_exist_query = mysqli_query($conn, "SELECT * FROM users WHERE email='$email' LIMIT 1");
            $exist = mysqli_num_rows($if_exist_query);
            // CHeck if user exists
            if ($exist > 0){
                
                $status_msg= '<div class="alert alert-danger alert-dismissible fade show" role="alert"><i class="fas fa-exclamation-triangle"></i> A user with this email already exist
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>';
            }else{
                // Register User
                move_uploaded_file($user_passport_tmp, "../assets/images/users/$rand$user_passport");
                
                
                $user_id = $client_abbreviation.date('Y').rand(1000,9999);
                $password = password_hash($user_id, PASSWORD_BCRYPT, ['cost' => 12]);    
             
             
             $result = mysqli_query($conn, "INSERT INTO `users`(`team`,`active_team`, `user_id`,`passport`, `role`, `fullname`, `status`, `subscription`, `password`, `email`, `phone`, `date`) VALUES ('$user_team_string','$user_team_string', '$user_id','$rand$user_passport','$user_type','$user_fullname','active','$subscription','$password','$email','$phone','$current_date_time')");

            //Get user id generated by database;
           $user_id_query = mysqli_query($conn, "SELECT id FROM users WHERE email='$email'");
           $user_gen_id = mysqli_fetch_assoc($user_id_query)['id'];
           
           //calculating the subscription due date.
          $sub_duration_query = mysqli_query($conn, "SELECT duration FROM subscription_plans WHERE id ='$subscription'");
           $sub_duration = mysqli_fetch_assoc($sub_duration_query)['duration'];
           if($sub_duration != 'INFINITE'){
               $sub_duration = $sub_duration * 30;
           }
          $due_date = add_dates($current_date_time, ($sub_duration));
           
           //Insert into user subscriptions table
           mysqli_query($conn, "INSERT INTO `user_subscriptions`(`type`, `subscriber`, `subscription_date`, `expiry_date`) VALUES ('$subscription','$user_gen_id','$current_date_time','$due_date')");
           $status_msg = '<div class="alert alert-success alert-dismissible fade show" role="alert"><i class="fas fa-check-circle"></i>  You successfully created the staff- ' . $user_fullname. '
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>';
                //Insert into activity log
                     mysqli_query($conn, "INSERT INTO `activity_log`(`team`, `date`, `activity`) VALUES ('$active_teams','$current_date_time','$current_user_name created the staff - $user_fullname')");

                
                
                // Mail function
                
                
                
                
                $mail->setFrom($mailuser, 'BT Support');
                $mail->addAddress($email, $user_fullname);
                
                $mail->isHTML(true); // Set email format to HTML
                $mail->Subject = 'Registered User';
                $mail->Body = '<html><body style="margin:0 auto;">
                     <center>  <img src="https://binaltechnologies.com/assets/img/btheader.png" alt="BT Header" /><br/>
                      <table rules="all"  cellpadding="10">
                      <p style="font-size:17px; line-height: 28px"> Your account has been successfully registered with ID- '. $user_id.'  . Sign in <a href="https://binalgist.com.ng/lms/login">here</a>  </p>
                      <p> Use your ID as your password. You can change it anytime on your profile page. </p>
                      
                        </table>
                    <img src="https://binaltechnologies.com/assets/img/btfooter.png" alt="BT Footer" /></center><br/>
                      </body></html>';
                
                $mail->send();
                
                
            }
        }
            
?>